export const cities = [
  { name: 'Accra Metropolitan ', price: 10 },
  { name: 'Accra Mall', price: 12 },
  { name: 'Action Chapel', price: 12 },
  { name: 'palace mall(spintex)', price: 12 },
  { name: 'Achimota', price: 12 },
  { name: 'Adabraka', price: 10 },
  { name: 'Adenta', price: 20 },
  { name: 'Abelemkpe', price: 10 },
  { name: 'Ablekuma', price: 20 },
  { name: 'Abofu', price: 20 },
  { name: 'Abokobi', price: 20 },
  { name: 'Abossey Okai', price: 10 },
  { name: 'Accra New Town', price: 10 },
  { name: 'Adjiriganor', price: 15 },
  { name: 'Agbogba', price: 15 },
  { name: 'Agbogbloshie', price: 10 },
  { name: 'Airport Residential Area', price: 12 },
  { name: 'Akweteyman', price: 12 },
  { name: 'Alajo', price: 10 },
  { name: 'Amassaman', price: 25 },
  { name: 'Anyaa', price: 20 },
  { name: 'Apenkwa', price: 13 },
  { name: 'Ashaiman Municipal', price: 25 },
  { name: 'Ashaley Botwe', price: 25 },
  { name: 'Ashomang Estate', price: 25 },
  { name: 'Asylum Down', price: 10 },
  { name: 'Atomic', price: 15 },
  { name: 'Avenor Area', price: 10 },
  { name: 'Awoshie', price: 15 },
  { name: 'Awudome', price: 7 },
  { name: 'Banana Inn', price: 10 },
  { name: 'Bubuashie', price: 7 },
  { name: 'Burma Camp', price: 15 },
  { name: 'Cantonments', price: 15 },
  { name: 'Central Business District', price: 15 },
  { name: 'Chorkor', price: 15 },
  { name: 'Circle', price: 10 },
  { name: 'Dansoman', price: 15 },
  { name: 'Darkuman', price: 10 },
  { name: 'Dodowa', price: 30 },
  { name: 'Dome', price: 18 },
  { name: 'Kwabenya', price: 20 },
  { name: 'Dzorwulu', price: 15 },
  { name: 'East Legon', price: 15 },
  { name: 'East Legon Hills', price: 20 },
  { name: 'Gbawe', price: 20 },
  { name: 'Haatso', price: 20 },
  { name: 'James Town', price: 15 },
  { name: 'Kaneshie', price: 7 },
  { name: 'Kokomlemle', price: 10 },
  { name: 'Korle Bu', price: 15 },
  { name: 'Korle Gonno', price: 18 },
  { name: 'Kotobabi', price: 10 },
  { name: 'Kwashieman', price: 12 },
  { name: 'Labadi', price: 15 },
  { name: 'Labone', price: 15 },
  { name: 'Lapaz', price: 12 },
  { name: 'Lartebiokorshie', price: 12 },
  { name: 'Ledzokuku-Krowor', price: 15 },
  { name: 'Madina', price: 15 },
  { name: 'Mamobi', price: 10 },
  { name: 'Mamprobi', price: 12 },
  { name: 'Mataheko', price: 20 },
  { name: 'New Mamprobi', price: 12 },
  { name: 'Nii Boi Town', price: 12 },
  { name: 'Nima', price: 10 },
  { name: 'North Industrial Area', price: 8 },
  { name: 'North Kaneshie', price: 8 },
  { name: 'Nungua', price: 15 },
  { name: 'Odorkor', price: 12 },
  { name: 'Ofankor', price: 13 },
  { name: 'Okaishie', price: 10 },
  { name: 'Okponglo', price: 10 },
  { name: 'Old Ashomang', price: 25 },
  { name: 'Osu', price: 10 },
  { name: 'Oyarifa', price: 35 },
  { name: 'Oyibi', price: 40 },
  { name: 'Pantang', price: 40 },
  { name: 'Pigfarm', price: 10 },
  { name: 'Pokuase', price: 35 },
  { name: 'North Ridge', price: 15 },
  { name: 'Roman Ridge', price: 15 },
  { name: 'SSNIT Flats', price: 25 },
  { name: 'Santa Maria', price: 15 },
  { name: 'Sempe New Town', price: 15 },
  { name: 'South La', price: 15 },
  { name: 'South Shiashie', price: 25 },
  { name: 'Sowutwuom', price: 15 },
  { name: 'Spintex', price: 25 },
  { name: 'Sukura', price: 15 },
  { name: 'Taifa-Burkina', price: 25 },
  { name: 'Taifa', price: 25 },
  { name: 'Tantra Hills', price: 25 },
  { name: 'Tema', price: 40 },
  { name: 'Kasoa', price: 30 },
  { name: 'Tesano', price: 10 },
  { name: 'Teshie', price: 20 },
  { name: 'Tudu', price: 15 },
  { name: 'University Of Ghana', price: 20 },
  { name: 'UPSA', price: 20 },
  { name: 'Weija', price: 25 },
  { name: 'West Legon', price: 20 },
  { name: 'Zoti Area', price: 15 },
  { name: 'Laterbiokoshie', price: 30 },
];
